CREATE TABLE feedback(
    NAME VARCHAR(20) NOT NULL,
    email VARCHAR(20) NOT NULL,
    tel VARCHAR(20) NOT NULL,
    DATE DATE NOT NULL,
    remarks VARCHAR(500) NOT NULL,
    PRIMARY KEY(NAME, DATE)
);